package com.msb.ibs.corp.cross.exchange.domain.entity;

import java.math.BigDecimal;
import java.util.Date;

public class BkAccountHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.CORE_SN
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private String coreSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.TRAN_SN
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private String tranSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.TRAN_SERVICE_CODE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private String tranServiceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.TRACE_CODE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private String traceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.DC_SIGN
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private String dcSign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.ACCEPTS_ORG
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private String acceptsOrg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.TRAN_TYPE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private String tranType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.TRAN_DEVICE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private String tranDevice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.DEVICE_NO
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private String deviceNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.VOUCHER_TYPE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private String voucherType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.CURRENCY_CODE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private String currencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.ROLLOUT_ACCT_NO
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private String rolloutAcctNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.ROLLOUT_ACCT_NAME
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private String rolloutAcctName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.ROLLOUT_CARD_NO
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private String rolloutCardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.BENEFICIARY_ACCT_NO
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private String beneficiaryAcctNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.BENEFICIARY_ACCT_NAME
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private String beneficiaryAcctName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.BENEFICIARY_ACCT_BANK
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private String beneficiaryAcctBank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.BENEFICIARY_ACCT_BRANCH
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private String beneficiaryAcctBranch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.BENEFICIARY_CARD_NO
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private String beneficiaryCardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.AMOUNT
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.FEE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private BigDecimal fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.PRE_BALANCE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private BigDecimal preBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.ACT_BALANCE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private BigDecimal actBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.POST_TIME
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private Date postTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.TRAN_TIME
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private Date tranTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.STATUS
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.OPERATOR
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.CHANNEL
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private String channel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.REMARK
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.INSERT_DATE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private Date insertDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.TELLER_ID
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private String tellerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.TM_SEQ
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private BigDecimal tmSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.SYNC_TYPE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private Integer syncType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.TC_CODE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private String tcCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.TC_SYNC_TIME
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private Date tcSyncTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.LN_TIME
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private String lnTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.DUE_DATE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private String dueDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BK_ACCOUNT_HISTORY.OS_BALANCE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    private BigDecimal osBalance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.CORE_SN
     *
     * @return the value of BK_ACCOUNT_HISTORY.CORE_SN
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public String getCoreSn() {
        return coreSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.CORE_SN
     *
     * @param coreSn the value for BK_ACCOUNT_HISTORY.CORE_SN
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setCoreSn(String coreSn) {
        this.coreSn = coreSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.TRAN_SN
     *
     * @return the value of BK_ACCOUNT_HISTORY.TRAN_SN
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public String getTranSn() {
        return tranSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.TRAN_SN
     *
     * @param tranSn the value for BK_ACCOUNT_HISTORY.TRAN_SN
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setTranSn(String tranSn) {
        this.tranSn = tranSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.TRAN_SERVICE_CODE
     *
     * @return the value of BK_ACCOUNT_HISTORY.TRAN_SERVICE_CODE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public String getTranServiceCode() {
        return tranServiceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.TRAN_SERVICE_CODE
     *
     * @param tranServiceCode the value for BK_ACCOUNT_HISTORY.TRAN_SERVICE_CODE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setTranServiceCode(String tranServiceCode) {
        this.tranServiceCode = tranServiceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.TRACE_CODE
     *
     * @return the value of BK_ACCOUNT_HISTORY.TRACE_CODE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public String getTraceCode() {
        return traceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.TRACE_CODE
     *
     * @param traceCode the value for BK_ACCOUNT_HISTORY.TRACE_CODE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setTraceCode(String traceCode) {
        this.traceCode = traceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.DC_SIGN
     *
     * @return the value of BK_ACCOUNT_HISTORY.DC_SIGN
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public String getDcSign() {
        return dcSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.DC_SIGN
     *
     * @param dcSign the value for BK_ACCOUNT_HISTORY.DC_SIGN
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setDcSign(String dcSign) {
        this.dcSign = dcSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.ACCEPTS_ORG
     *
     * @return the value of BK_ACCOUNT_HISTORY.ACCEPTS_ORG
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public String getAcceptsOrg() {
        return acceptsOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.ACCEPTS_ORG
     *
     * @param acceptsOrg the value for BK_ACCOUNT_HISTORY.ACCEPTS_ORG
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setAcceptsOrg(String acceptsOrg) {
        this.acceptsOrg = acceptsOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.TRAN_TYPE
     *
     * @return the value of BK_ACCOUNT_HISTORY.TRAN_TYPE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public String getTranType() {
        return tranType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.TRAN_TYPE
     *
     * @param tranType the value for BK_ACCOUNT_HISTORY.TRAN_TYPE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setTranType(String tranType) {
        this.tranType = tranType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.TRAN_DEVICE
     *
     * @return the value of BK_ACCOUNT_HISTORY.TRAN_DEVICE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public String getTranDevice() {
        return tranDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.TRAN_DEVICE
     *
     * @param tranDevice the value for BK_ACCOUNT_HISTORY.TRAN_DEVICE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setTranDevice(String tranDevice) {
        this.tranDevice = tranDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.DEVICE_NO
     *
     * @return the value of BK_ACCOUNT_HISTORY.DEVICE_NO
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public String getDeviceNo() {
        return deviceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.DEVICE_NO
     *
     * @param deviceNo the value for BK_ACCOUNT_HISTORY.DEVICE_NO
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setDeviceNo(String deviceNo) {
        this.deviceNo = deviceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.VOUCHER_TYPE
     *
     * @return the value of BK_ACCOUNT_HISTORY.VOUCHER_TYPE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public String getVoucherType() {
        return voucherType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.VOUCHER_TYPE
     *
     * @param voucherType the value for BK_ACCOUNT_HISTORY.VOUCHER_TYPE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setVoucherType(String voucherType) {
        this.voucherType = voucherType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.CURRENCY_CODE
     *
     * @return the value of BK_ACCOUNT_HISTORY.CURRENCY_CODE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.CURRENCY_CODE
     *
     * @param currencyCode the value for BK_ACCOUNT_HISTORY.CURRENCY_CODE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.ROLLOUT_ACCT_NO
     *
     * @return the value of BK_ACCOUNT_HISTORY.ROLLOUT_ACCT_NO
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public String getRolloutAcctNo() {
        return rolloutAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.ROLLOUT_ACCT_NO
     *
     * @param rolloutAcctNo the value for BK_ACCOUNT_HISTORY.ROLLOUT_ACCT_NO
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setRolloutAcctNo(String rolloutAcctNo) {
        this.rolloutAcctNo = rolloutAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.ROLLOUT_ACCT_NAME
     *
     * @return the value of BK_ACCOUNT_HISTORY.ROLLOUT_ACCT_NAME
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public String getRolloutAcctName() {
        return rolloutAcctName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.ROLLOUT_ACCT_NAME
     *
     * @param rolloutAcctName the value for BK_ACCOUNT_HISTORY.ROLLOUT_ACCT_NAME
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setRolloutAcctName(String rolloutAcctName) {
        this.rolloutAcctName = rolloutAcctName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.ROLLOUT_CARD_NO
     *
     * @return the value of BK_ACCOUNT_HISTORY.ROLLOUT_CARD_NO
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public String getRolloutCardNo() {
        return rolloutCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.ROLLOUT_CARD_NO
     *
     * @param rolloutCardNo the value for BK_ACCOUNT_HISTORY.ROLLOUT_CARD_NO
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setRolloutCardNo(String rolloutCardNo) {
        this.rolloutCardNo = rolloutCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.BENEFICIARY_ACCT_NO
     *
     * @return the value of BK_ACCOUNT_HISTORY.BENEFICIARY_ACCT_NO
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public String getBeneficiaryAcctNo() {
        return beneficiaryAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.BENEFICIARY_ACCT_NO
     *
     * @param beneficiaryAcctNo the value for BK_ACCOUNT_HISTORY.BENEFICIARY_ACCT_NO
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setBeneficiaryAcctNo(String beneficiaryAcctNo) {
        this.beneficiaryAcctNo = beneficiaryAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.BENEFICIARY_ACCT_NAME
     *
     * @return the value of BK_ACCOUNT_HISTORY.BENEFICIARY_ACCT_NAME
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public String getBeneficiaryAcctName() {
        return beneficiaryAcctName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.BENEFICIARY_ACCT_NAME
     *
     * @param beneficiaryAcctName the value for BK_ACCOUNT_HISTORY.BENEFICIARY_ACCT_NAME
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setBeneficiaryAcctName(String beneficiaryAcctName) {
        this.beneficiaryAcctName = beneficiaryAcctName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.BENEFICIARY_ACCT_BANK
     *
     * @return the value of BK_ACCOUNT_HISTORY.BENEFICIARY_ACCT_BANK
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public String getBeneficiaryAcctBank() {
        return beneficiaryAcctBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.BENEFICIARY_ACCT_BANK
     *
     * @param beneficiaryAcctBank the value for BK_ACCOUNT_HISTORY.BENEFICIARY_ACCT_BANK
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setBeneficiaryAcctBank(String beneficiaryAcctBank) {
        this.beneficiaryAcctBank = beneficiaryAcctBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.BENEFICIARY_ACCT_BRANCH
     *
     * @return the value of BK_ACCOUNT_HISTORY.BENEFICIARY_ACCT_BRANCH
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public String getBeneficiaryAcctBranch() {
        return beneficiaryAcctBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.BENEFICIARY_ACCT_BRANCH
     *
     * @param beneficiaryAcctBranch the value for BK_ACCOUNT_HISTORY.BENEFICIARY_ACCT_BRANCH
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setBeneficiaryAcctBranch(String beneficiaryAcctBranch) {
        this.beneficiaryAcctBranch = beneficiaryAcctBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.BENEFICIARY_CARD_NO
     *
     * @return the value of BK_ACCOUNT_HISTORY.BENEFICIARY_CARD_NO
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public String getBeneficiaryCardNo() {
        return beneficiaryCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.BENEFICIARY_CARD_NO
     *
     * @param beneficiaryCardNo the value for BK_ACCOUNT_HISTORY.BENEFICIARY_CARD_NO
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setBeneficiaryCardNo(String beneficiaryCardNo) {
        this.beneficiaryCardNo = beneficiaryCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.AMOUNT
     *
     * @return the value of BK_ACCOUNT_HISTORY.AMOUNT
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.AMOUNT
     *
     * @param amount the value for BK_ACCOUNT_HISTORY.AMOUNT
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.FEE
     *
     * @return the value of BK_ACCOUNT_HISTORY.FEE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.FEE
     *
     * @param fee the value for BK_ACCOUNT_HISTORY.FEE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.PRE_BALANCE
     *
     * @return the value of BK_ACCOUNT_HISTORY.PRE_BALANCE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public BigDecimal getPreBalance() {
        return preBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.PRE_BALANCE
     *
     * @param preBalance the value for BK_ACCOUNT_HISTORY.PRE_BALANCE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setPreBalance(BigDecimal preBalance) {
        this.preBalance = preBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.ACT_BALANCE
     *
     * @return the value of BK_ACCOUNT_HISTORY.ACT_BALANCE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public BigDecimal getActBalance() {
        return actBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.ACT_BALANCE
     *
     * @param actBalance the value for BK_ACCOUNT_HISTORY.ACT_BALANCE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setActBalance(BigDecimal actBalance) {
        this.actBalance = actBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.POST_TIME
     *
     * @return the value of BK_ACCOUNT_HISTORY.POST_TIME
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public Date getPostTime() {
        return postTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.POST_TIME
     *
     * @param postTime the value for BK_ACCOUNT_HISTORY.POST_TIME
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setPostTime(Date postTime) {
        this.postTime = postTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.TRAN_TIME
     *
     * @return the value of BK_ACCOUNT_HISTORY.TRAN_TIME
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public Date getTranTime() {
        return tranTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.TRAN_TIME
     *
     * @param tranTime the value for BK_ACCOUNT_HISTORY.TRAN_TIME
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setTranTime(Date tranTime) {
        this.tranTime = tranTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.STATUS
     *
     * @return the value of BK_ACCOUNT_HISTORY.STATUS
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.STATUS
     *
     * @param status the value for BK_ACCOUNT_HISTORY.STATUS
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.OPERATOR
     *
     * @return the value of BK_ACCOUNT_HISTORY.OPERATOR
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.OPERATOR
     *
     * @param operator the value for BK_ACCOUNT_HISTORY.OPERATOR
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.CHANNEL
     *
     * @return the value of BK_ACCOUNT_HISTORY.CHANNEL
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.CHANNEL
     *
     * @param channel the value for BK_ACCOUNT_HISTORY.CHANNEL
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setChannel(String channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.REMARK
     *
     * @return the value of BK_ACCOUNT_HISTORY.REMARK
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.REMARK
     *
     * @param remark the value for BK_ACCOUNT_HISTORY.REMARK
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.INSERT_DATE
     *
     * @return the value of BK_ACCOUNT_HISTORY.INSERT_DATE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public Date getInsertDate() {
        return insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.INSERT_DATE
     *
     * @param insertDate the value for BK_ACCOUNT_HISTORY.INSERT_DATE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.TELLER_ID
     *
     * @return the value of BK_ACCOUNT_HISTORY.TELLER_ID
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public String getTellerId() {
        return tellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.TELLER_ID
     *
     * @param tellerId the value for BK_ACCOUNT_HISTORY.TELLER_ID
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setTellerId(String tellerId) {
        this.tellerId = tellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.TM_SEQ
     *
     * @return the value of BK_ACCOUNT_HISTORY.TM_SEQ
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public BigDecimal getTmSeq() {
        return tmSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.TM_SEQ
     *
     * @param tmSeq the value for BK_ACCOUNT_HISTORY.TM_SEQ
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setTmSeq(BigDecimal tmSeq) {
        this.tmSeq = tmSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.SYNC_TYPE
     *
     * @return the value of BK_ACCOUNT_HISTORY.SYNC_TYPE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public Integer getSyncType() {
        return syncType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.SYNC_TYPE
     *
     * @param syncType the value for BK_ACCOUNT_HISTORY.SYNC_TYPE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setSyncType(Integer syncType) {
        this.syncType = syncType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.TC_CODE
     *
     * @return the value of BK_ACCOUNT_HISTORY.TC_CODE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public String getTcCode() {
        return tcCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.TC_CODE
     *
     * @param tcCode the value for BK_ACCOUNT_HISTORY.TC_CODE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setTcCode(String tcCode) {
        this.tcCode = tcCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.TC_SYNC_TIME
     *
     * @return the value of BK_ACCOUNT_HISTORY.TC_SYNC_TIME
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public Date getTcSyncTime() {
        return tcSyncTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.TC_SYNC_TIME
     *
     * @param tcSyncTime the value for BK_ACCOUNT_HISTORY.TC_SYNC_TIME
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setTcSyncTime(Date tcSyncTime) {
        this.tcSyncTime = tcSyncTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.LN_TIME
     *
     * @return the value of BK_ACCOUNT_HISTORY.LN_TIME
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public String getLnTime() {
        return lnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.LN_TIME
     *
     * @param lnTime the value for BK_ACCOUNT_HISTORY.LN_TIME
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setLnTime(String lnTime) {
        this.lnTime = lnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.DUE_DATE
     *
     * @return the value of BK_ACCOUNT_HISTORY.DUE_DATE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public String getDueDate() {
        return dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.DUE_DATE
     *
     * @param dueDate the value for BK_ACCOUNT_HISTORY.DUE_DATE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setDueDate(String dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BK_ACCOUNT_HISTORY.OS_BALANCE
     *
     * @return the value of BK_ACCOUNT_HISTORY.OS_BALANCE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public BigDecimal getOsBalance() {
        return osBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BK_ACCOUNT_HISTORY.OS_BALANCE
     *
     * @param osBalance the value for BK_ACCOUNT_HISTORY.OS_BALANCE
     *
     * @mbg.generated Thu May 16 16:53:17 ICT 2019
     */
    public void setOsBalance(BigDecimal osBalance) {
        this.osBalance = osBalance;
    }
}
